server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_learn?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
