server:
  port: 8081

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates

  profiles:
    active: dev
#    active: test

  application:
#    name: @artifactId@
    name: spring-boot-learn

  datasource:
    url: jdbc:mysql://localhost:3306/db01?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

#  mvc:
#    content-negotiation:
#      media-types:
#        json: application/json


  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.spring.boot.learn.mapper
